In [9]:
import pandas as pd

years = [2020, 2021, 2022, 2023, 2024, 2025]
dfs = []
for year in years:
    for quarter in ['Q1', 'Q2', 'Q3', 'Q4']:
        file_path = f"../data/raw/BDD PRODUCCION/BDD PRODUCCION/{year}/{quarter} {year}.csv"
        try:
            df = pd.read_csv(file_path)
            dfs.append(df)
        except FileNotFoundError as e:
            print(f"File not found: {file_path}, error: {e}")
            pass 

remissions = pd.concat(dfs, ignore_index=True)
remissions.head(-1)

,Year,tkt_code,order_date,order_code,start_time,truck_code,ship_plant_code,u_Volumen,typed_time,at_plant_time,u_Cicle,name,Nombre del proyecto,ship_addr_line,map_page
0,2020,51013232,2020-02-04 00:00:00,1073,2020-02-04 07:00:00,7044,510,6.0,2020-02-04 06:45:13,2020-02-04 08:17:24,92,ONE TIME OCTAVIO RIOS,ARMENDARIZ ARMANDO,HACIENDAS HENEKENERAS 2679 GRACC HACIEND,CH-F1
1,2020,51013233,2020-02-04 00:00:00,1073,2020-02-04 07:00:00,6603,510,5.5,2020-02-04 06:45:22,2020-02-04 08:26:06,101,ONE TIME OCTAVIO RIOS,ARMENDARIZ ARMANDO,HACIENDAS HENEKENERAS 2679 GRACC HACIEND,CH-F1
2,2020,51013235,2020-02-04 00:00:00,1028,2020-02-04 08:00:00,9631,510,2.5,2020-02-04 07:37:56,2020-02-04 08:55:49,78,ONE TIME ESP ANGELICA RIVERA GOMEZ,ROMERO JULIA,CALLE MANUEL BECERRA 14515 COL ALAMEDAS,CH-F5
3,2020,51013236,2020-02-04 00:00:00,1005,2020-02-04 08:15:00,6598,510,3.0,2020-02-04 08:02:36,2020-02-04 09:47:43,105,IVAN NOE SIMENTAL ORTEGA,COLECTOR SACRAMENTO,ARROLLO MIMBRE Y VIALIDAD SACRAMENTO,CH-J9
4,2020,51013238,2020-02-04 00:00:00,1026,2020-02-04 08:30:00,10145,510,3.5,2020-02-04 08:09:01,2020-02-04 09:09:15,60,ONE TIME CONSTRUCENTRO CHIH,MOLINA BALDERRAMA CESAR,PERIF DE LA JUVENTUD 9926 COL RESIDENCIA,CH-L5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340768,2026,71037451,2026-01-31 00:00:00,1069,2026-01-31 11:00:00,13053,710,2.0,2026-01-31 10:06:20,2026-01-31 11:03:20,57,BENJAMIN MATA CONDE,VILLAS LA HACIENDITA,EJIDO LA HACIENDITA S/N CHIHUAHUA,CHP-4
340769,2026,71037452,2026-01-31 00:00:00,1073,2026-01-31 10:00:00,12831,710,3.0,2026-01-31 10:36:44,2026-01-31 10:50:38,14,FERRETERIA MOLINA DE CHIHUAHUA,FERRETERIA MOLINA DE CHIHUAHUA,FRACC DOMINIO LOTE 2 MANZANA 10,CHN-3
340770,2026,71037453,2026-01-31 00:00:00,1244,2026-01-31 10:00:00,12831,710,0.5,2026-01-31 10:51:48,2026-01-31 13:01:36,130,FERRETERIA MOLINA DE CHIHUAHUA,FERRETERIA MOLINA DE CHIHUAHUA,FRACC DOMINIO LOTE 2 MANZANA 10,CHN-3
340771,2026,71037454,2026-01-31 00:00:00,1070,2026-01-31 12:00:00,13041,710,2.5,2026-01-31 10:55:54,2026-01-31 12:52:16,117,ALFONSO ORTEGA ANTILLON,FRAC ALCAZARES (MYKONOS),AVE DE LA CANTERA SN ALCAZARES (MYKON,CHP-3
340772,2026,71037455,2026-01-31 00:00:00,1188,2026-01-31 12:45:00,12829,710,4.5,2026-01-31 12:07:07,2026-01-31 12:52:23,45,PROMOTORES MEXICANOS DE LA EDUCACIO,PROMOTORES MEXICANOS DE LA EDUCACIO,AV CANTERA S/N COLEGIO REGIONAL DEL NORT,CHP-1

In [12]:
print("Number of rows in remissions DataFrame:", remissions.shape[0])
print("Number of columns in remissions DataFrame:", remissions.shape[1])

Number of rows in remissions DataFrame: 340774
Number of columns in remissions DataFrame: 15

In [14]:
remissions.info()

<class 'pandas.DataFrame'>
RangeIndex: 340774 entries, 0 to 340773
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Year                 340774 non-null  int64
 1   tkt_code             340774 non-null  int64
 2   order_date           340774 non-null  str
 3   order_code           340774 non-null  int64
 4   start_time           340774 non-null  str
 5   truck_code           340774 non-null  int64
 6   ship_plant_code      340774 non-null  int64
 7   u_Volumen            340774 non-null  float64
 8   typed_time           340774 non-null  str
 9   at_plant_time        340774 non-null  str
 10  u_Cicle              340774 non-null  int64
 11  name                 340773 non-null  str
 12  Nombre del proyecto  340774 non-null  str
 13  ship_addr_line       340689 non-null  str
 14  map_page             340330 non-null  str
dtypes: float64(1), int64(6), str(8)
memory usage: 92.9 MB

In [15]:
remissions.describe()

,Year,tkt_code,order_code,truck_code,ship_plant_code,u_Volumen,u_Cicle
count,340774.000000,3.407740e+05,340774.000000,340774.000000,340774.000000,340774.000000,340774.000000
mean,2022.651860,5.398165e+07,1183.753106,8538.253552,539.312647,3.189403,77.168880
std,1.700824,6.823326e+06,134.179106,2806.780018,68.249967,1.782878,35.884389
min,2020.000000,5.100000e+07,1000.000000,4216.000000,510.000000,0.340000,1.000000
25%,2021.000000,5.112677e+07,1091.000000,6301.000000,511.000000,1.500000,56.000000
50%,2023.000000,5.126167e+07,1170.000000,9428.000000,512.000000,3.000000,74.000000
75%,2024.000000,5.152497e+07,1258.000000,10149.000000,515.000000,5.000000,96.000000
max,2026.000000,7.173652e+07,9636.000000,13221.000000,717.000000,6.500000,209.000000

In [16]:
remissions.isnull().sum()

Year                     0
tkt_code                 0
order_date               0
order_code               0
start_time               0
truck_code               0
ship_plant_code          0
u_Volumen                0
typed_time               0
at_plant_time            0
u_Cicle                  0
name                     1
Nombre del proyecto      0
ship_addr_line          85
map_page               444
dtype: int64

In [26]:
# Identify rows where both 'ship_addr_line' and 'map_page' are null
remissions[(remissions['ship_addr_line'].isnull() == True) & (remissions['map_page'].isnull() == True)]

Empty DataFrame
Columns: [Year, tkt_code, order_date, order_code, start_time, truck_code, ship_plant_code, u_Volumen, typed_time, at_plant_time, u_Cicle, name, Nombre del proyecto, ship_addr_line, map_page]
Index: []

In [ ]:
#Null checking
remissions_percentage_null = remissions.isnull().mean() * 100
print(remissions_percentage_null)

Year                   0.000000
tkt_code               0.000000
order_date             0.000000
order_code             0.000000
start_time             0.000000
truck_code             0.000000
ship_plant_code        0.000000
u_Volumen              0.000000
typed_time             0.000000
at_plant_time          0.000000
u_Cicle                0.000000
name                   0.000293
Nombre del proyecto    0.000000
ship_addr_line         0.024943
map_page               0.130292
dtype: float64

In [ ]:
#Duplicate checking, where tkc_code can be different
cols_to_check = [col for col in remissions.columns if col != 'tkt_code']
remissions.duplicated(subset=cols_to_check, keep=False).sum()

np.int64(0)

In [45]:
remissions.head()

,Year,tkt_code,order_date,order_code,start_time,truck_code,ship_plant_code,u_Volumen,typed_time,at_plant_time,u_Cicle,name,Nombre del proyecto,ship_addr_line,map_page
0,2020,51013232,2020-02-04 00:00:00,1073,2020-02-04 07:00:00,7044,510,6.0,2020-02-04 06:45:13,2020-02-04 08:17:24,92,ONE TIME OCTAVIO RIOS,ARMENDARIZ ARMANDO,HACIENDAS HENEKENERAS 2679 GRACC HACIEND,CH-F1
1,2020,51013233,2020-02-04 00:00:00,1073,2020-02-04 07:00:00,6603,510,5.5,2020-02-04 06:45:22,2020-02-04 08:26:06,101,ONE TIME OCTAVIO RIOS,ARMENDARIZ ARMANDO,HACIENDAS HENEKENERAS 2679 GRACC HACIEND,CH-F1
2,2020,51013235,2020-02-04 00:00:00,1028,2020-02-04 08:00:00,9631,510,2.5,2020-02-04 07:37:56,2020-02-04 08:55:49,78,ONE TIME ESP ANGELICA RIVERA GOMEZ,ROMERO JULIA,CALLE MANUEL BECERRA 14515 COL ALAMEDAS,CH-F5
3,2020,51013236,2020-02-04 00:00:00,1005,2020-02-04 08:15:00,6598,510,3.0,2020-02-04 08:02:36,2020-02-04 09:47:43,105,IVAN NOE SIMENTAL ORTEGA,COLECTOR SACRAMENTO,ARROLLO MIMBRE Y VIALIDAD SACRAMENTO,CH-J9
4,2020,51013238,2020-02-04 00:00:00,1026,2020-02-04 08:30:00,10145,510,3.5,2020-02-04 08:09:01,2020-02-04 09:09:15,60,ONE TIME CONSTRUCENTRO CHIH,MOLINA BALDERRAMA CESAR,PERIF DE LA JUVENTUD 9926 COL RESIDENCIA,CH-L5

In [ ]:
# See rows where typed time, order_date and start_time are duplicated, which could be a sign of duplicates.
typed_time_duplicates = remissions[remissions.duplicated(subset=['typed_time', 'order_date', 'start_time'], keep=False)]
typed_time_duplicates = typed_time_duplicates.sort_values(by='typed_time', ascending=True)

typed_time_duplicates.head(10)

,Year,tkt_code,order_date,order_code,start_time,truck_code,ship_plant_code,u_Volumen,typed_time,at_plant_time,u_Cicle,name,Nombre del proyecto,ship_addr_line,map_page
296720,2025,51011084,6/17/2025,1352,10:45:00 AM,9428,510,3.0,10:59:14 AM,12:18:33 PM,79,JOSE LUIS RODRIGUEZ SOLIS,PROLONGACION AV HACIENDAS DEL VALLE,PROLONGACION AV HACIENDAS DEL VALLE S/N,CHQ-5
307474,2025,51583602,6/17/2025,1301,10:45:00 AM,12833,515,2.0,10:59:14 AM,12:12:18 PM,73,RUBA DESARROLLOS,LUIS VELEZ JARDINES DE SAN AGUSTUN,LUIS VELEZ JARDINES DE SAN AGUSTIN 2 SN,CHR-21
300423,2025,51267948,5/3/2025,1146,10:30:00 AM,9429,512,5.5,11:34:06 AM,12:43:41 PM,69,ADMINISTRACION DE PROYECTOS DE CHIH,CONSTRUCCION DE POZO 1 ZIUDANA,CARR CHIH-MIGUEL AHUMADA KM 17 S/N EN,CHD-1
306137,2025,51581491,5/3/2025,1262,10:30:00 AM,12832,515,2.0,11:34:06 AM,12:21:25 PM,47,JOSE CARRILLO RAMIREZ,FRAC MISION DE SAN IGNACIO,AV. EQUUS Y ENCINO DE ASTA JUNTO AL FRAC,CHM-21
295355,2025,51008982,5/7/2025,1222,12:30:00 PM,9431,510,1.0,12:13:34 PM,1:00:25 PM,47,MARIA MAGDALENA CAMPOS BAQUERA,FRAC MONTE XENIT (DEXE),FRAC MONTE XENIT (DEXE) S/N FRAC MONT,CHH-1
309036,2025,71031152,5/7/2025,1062,12:30:00 PM,10157,710,2.5,12:13:34 PM,1:07:25 PM,54,MYKONOS,JIDASA FRACC ALCAZARES,CATEDRAL DE CHIH S/N FRACC ALCAZARES,CHP-2
301325,2025,51269439,5/28/2025,1304,12:45:00 PM,13022,512,1.0,12:14:26 PM,1:19:39 PM,65,RUBA DESARROLLOS,HANNA RAMIREZ VISTAS DEL NORTE,HANNA RAMIREZ VISTAS DEL NORTE SN IV,CHA-2
306889,2025,51582623,5/28/2025,1107,12:45:00 PM,13218,515,6.0,12:14:26 PM,2:27:38 PM,133,CORPORATIVO INMOBILIARIO DEL NORTE,FRACC DEL VALLE,FRAC DEL VALLE S/N FRAC DEL VALLE CHI,CHQ-21
305196,2025,51414319,7/5/2025,1140,12:15:00 PM,13012,514,3.5,12:52:23 PM,2:24:17 PM,92,JUAN CARLOS CANO DEL VAL,JUAN CARLOS CANO DEL VAL,CALLE JIMENEZ ESQ CON CALLE TERCERA COL,CHP-10
310077,2025,71032802,7/5/2025,1243,12:15:00 PM,13040,710,4.0,12:52:23 PM,1:39:31 PM,47,CONSTRUCTORA PROURVIKA,TORRE ALTEZA,JUAN DOMINGUEZ 801 SAN FELIPE ETAPA I,CHN-4

In [56]:
typed_time_duplicates['typed_time'].count()
percentage_typed_time_duplicates = (typed_time_duplicates['typed_time'].count() / remissions.shape[0]) * 100
print(f"Percentage of rows with duplicated typed_time, order_date and start_time: {percentage_typed_time_duplicates:.2f}%")

Percentage of rows with duplicated typed_time, order_date and start_time: 0.07%

None of them where same truck, plant, not order_code, meaning they are not duplicates, only time coincidences that have ocurred less than 300 times throughout >5 years (0.07%)

In [ ]:
# See columns where

In [ ]:
#DONE: Concatenated untouched csv files
#remissions.to_csv("../data/processed/remissions_db.csv", index=False)