In [2]:
import pandas as pd

In [3]:
remissions_df = pd.read_csv("../data/processed/remissions_db.csv")
remissions_df.head(-1)

,Year,tkt_code,order_date,order_code,start_time,truck_code,ship_plant_code,u_Volumen,typed_time,at_plant_time,u_Cicle,name,Nombre del proyecto,ship_addr_line,map_page
0,2020,51013232,2020-02-04 00:00:00,1073,2020-02-04 07:00:00,7044,510,6.0,2020-02-04 06:45:13,2020-02-04 08:17:24,92,ONE TIME OCTAVIO RIOS,ARMENDARIZ ARMANDO,HACIENDAS HENEKENERAS 2679 GRACC HACIEND,CH-F1
1,2020,51013233,2020-02-04 00:00:00,1073,2020-02-04 07:00:00,6603,510,5.5,2020-02-04 06:45:22,2020-02-04 08:26:06,101,ONE TIME OCTAVIO RIOS,ARMENDARIZ ARMANDO,HACIENDAS HENEKENERAS 2679 GRACC HACIEND,CH-F1
2,2020,51013235,2020-02-04 00:00:00,1028,2020-02-04 08:00:00,9631,510,2.5,2020-02-04 07:37:56,2020-02-04 08:55:49,78,ONE TIME ESP ANGELICA RIVERA GOMEZ,ROMERO JULIA,CALLE MANUEL BECERRA 14515 COL ALAMEDAS,CH-F5
3,2020,51013236,2020-02-04 00:00:00,1005,2020-02-04 08:15:00,6598,510,3.0,2020-02-04 08:02:36,2020-02-04 09:47:43,105,IVAN NOE SIMENTAL ORTEGA,COLECTOR SACRAMENTO,ARROLLO MIMBRE Y VIALIDAD SACRAMENTO,CH-J9
4,2020,51013238,2020-02-04 00:00:00,1026,2020-02-04 08:30:00,10145,510,3.5,2020-02-04 08:09:01,2020-02-04 09:09:15,60,ONE TIME CONSTRUCENTRO CHIH,MOLINA BALDERRAMA CESAR,PERIF DE LA JUVENTUD 9926 COL RESIDENCIA,CH-L5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340768,2026,71037451,2026-01-31 00:00:00,1069,2026-01-31 11:00:00,13053,710,2.0,2026-01-31 10:06:20,2026-01-31 11:03:20,57,BENJAMIN MATA CONDE,VILLAS LA HACIENDITA,EJIDO LA HACIENDITA S/N CHIHUAHUA,CHP-4
340769,2026,71037452,2026-01-31 00:00:00,1073,2026-01-31 10:00:00,12831,710,3.0,2026-01-31 10:36:44,2026-01-31 10:50:38,14,FERRETERIA MOLINA DE CHIHUAHUA,FERRETERIA MOLINA DE CHIHUAHUA,FRACC DOMINIO LOTE 2 MANZANA 10,CHN-3
340770,2026,71037453,2026-01-31 00:00:00,1244,2026-01-31 10:00:00,12831,710,0.5,2026-01-31 10:51:48,2026-01-31 13:01:36,130,FERRETERIA MOLINA DE CHIHUAHUA,FERRETERIA MOLINA DE CHIHUAHUA,FRACC DOMINIO LOTE 2 MANZANA 10,CHN-3
340771,2026,71037454,2026-01-31 00:00:00,1070,2026-01-31 12:00:00,13041,710,2.5,2026-01-31 10:55:54,2026-01-31 12:52:16,117,ALFONSO ORTEGA ANTILLON,FRAC ALCAZARES (MYKONOS),AVE DE LA CANTERA SN ALCAZARES (MYKON,CHP-3
340772,2026,71037455,2026-01-31 00:00:00,1188,2026-01-31 12:45:00,12829,710,4.5,2026-01-31 12:07:07,2026-01-31 12:52:23,45,PROMOTORES MEXICANOS DE LA EDUCACIO,PROMOTORES MEXICANOS DE LA EDUCACIO,AV CANTERA S/N COLEGIO REGIONAL DEL NORT,CHP-1

In [4]:
# Based on EDA analysis, it´s okay to drop rows with null values (<2%)
remissions_df = remissions_df[remissions_df['ship_addr_line'].notnull() & remissions_df['map_page'].notnull() & remissions_df['name'].notnull()]
print("Number of rows after dropping null values:", remissions_df.shape[0])

Number of rows after dropping null values: 340244

In [5]:
# Change 'order_date' and 'typed_time' to datetime format
remissions_df['order_date'] = pd.to_datetime(remissions_df['order_date'], errors='raise', format='mixed')
remissions_df['typed_time'] = pd.to_datetime(remissions_df['typed_time'], errors='raise', format='mixed')
remissions_df['start_time'] = pd.to_datetime(remissions_df['start_time'], errors='raise', format='mixed')
remissions_df['at_plant_time'] = pd.to_datetime(remissions_df['at_plant_time'], errors='raise', format='mixed')
remissions_df.info()

<class 'pandas.DataFrame'>
Index: 340244 entries, 0 to 340773
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Year                 340244 non-null  int64
 1   tkt_code             340244 non-null  int64
 2   order_date           340244 non-null  datetime64[us]
 3   order_code           340244 non-null  int64
 4   start_time           340244 non-null  datetime64[us]
 5   truck_code           340244 non-null  int64
 6   ship_plant_code      340244 non-null  int64
 7   u_Volumen            340244 non-null  float64
 8   typed_time           340244 non-null  datetime64[us]
 9   at_plant_time        340244 non-null  datetime64[us]
 10  u_Cicle              340244 non-null  int64
 11  name                 340244 non-null  str
 12  Nombre del proyecto  340244 non-null  str
 13  ship_addr_line       340244 non-null  str
 14  map_page             340244 non-null  str
dtypes: datetime64[us](4), float64(1), int64(6), str(4)
memory usage: 71.3 MB

In [6]:
typed_time_duplicates = remissions_df[remissions_df.duplicated(subset=['start_time', 'at_plant_time','truck_code'], keep=False)]
typed_time_duplicates = typed_time_duplicates.sort_values(by='typed_time', ascending=True)
typed_time_duplicates.head(10)

,Year,tkt_code,order_date,order_code,start_time,truck_code,ship_plant_code,u_Volumen,typed_time,at_plant_time,u_Cicle,name,Nombre del proyecto,ship_addr_line,map_page
77566,2021,51038180,2021-08-12,1155,2021-08-12 10:00:00,6163,510,5.0,2021-08-12 10:22:43,2021-08-12 11:54:06,92,PLANEACION INMOBILIARIA DE,QUORUM COMERCIAL,CITADELA SECTOR 49 FRACC 63 QUORUM COME,CH-N1
77567,2021,51038180,2021-08-30,1243,2021-08-12 10:00:00,6163,510,5.0,2021-08-12 10:22:43,2021-08-12 11:54:06,92,PLANEACION INMOBILIARIA DE,QUORUM COMERCIAL,CITADELA SECTOR 49 FRACC 63 QUORUM COME,CH-N1
77575,2021,51038191,2021-08-12,1155,2021-08-12 10:00:00,9430,510,5.0,2021-08-12 11:39:18,2021-08-12 12:32:11,53,PLANEACION INMOBILIARIA DE,QUORUM COMERCIAL,CITADELA SECTOR 49 FRACC 63 QUORUM COME,CH-N1
77576,2021,51038191,2021-08-30,1243,2021-08-12 10:00:00,9430,510,5.0,2021-08-12 11:39:18,2021-08-12 12:32:11,53,PLANEACION INMOBILIARIA DE,QUORUM COMERCIAL,CITADELA SECTOR 49 FRACC 63 QUORUM COME,CH-N1
77579,2021,51038194,2021-08-12,1155,2021-08-12 10:00:00,9431,510,5.5,2021-08-12 12:00:53,2021-08-12 13:22:00,82,PLANEACION INMOBILIARIA DE,QUORUM COMERCIAL,CITADELA SECTOR 49 FRACC 63 QUORUM COME,CH-N1
77580,2021,51038194,2021-08-30,1243,2021-08-12 10:00:00,9431,510,5.5,2021-08-12 12:00:53,2021-08-12 13:22:00,82,PLANEACION INMOBILIARIA DE,QUORUM COMERCIAL,CITADELA SECTOR 49 FRACC 63 QUORUM COME,CH-N1
77582,2021,51038199,2021-08-12,1155,2021-08-12 10:00:00,10145,510,5.5,2021-08-12 12:20:39,2021-08-12 14:02:20,102,PLANEACION INMOBILIARIA DE,QUORUM COMERCIAL,CITADELA SECTOR 49 FRACC 63 QUORUM COME,CH-N1
77583,2021,51038199,2021-08-30,1243,2021-08-12 10:00:00,10145,510,5.5,2021-08-12 12:20:39,2021-08-12 14:02:20,102,PLANEACION INMOBILIARIA DE,QUORUM COMERCIAL,CITADELA SECTOR 49 FRACC 63 QUORUM COME,CH-N1
77743,2021,51038418,2021-08-17,1074,2021-08-17 07:30:00,10157,510,6.5,2021-08-17 07:17:00,2021-08-17 08:27:28,70,MATERIALES INDUSTRIALES DE,SANTA CLARA PONENTE,TABACALERAS YA RROYO EL CALORIENTO S,CH-G2
77744,2021,51038418,2021-08-20,1336,2021-08-17 07:30:00,10157,510,6.5,2021-08-17 07:17:00,2021-08-17 08:27:28,70,MATERIALES INDUSTRIALES DE,SANTA CLARA PONENTE,TABACALERAS YA RROYO EL CALORIENTO S,CH-G2

In [7]:
typed_time_duplicates.count()

Year                   24
tkt_code               24
order_date             24
order_code             24
start_time             24
truck_code             24
ship_plant_code        24
u_Volumen              24
typed_time             24
at_plant_time          24
u_Cicle                24
name                   24
Nombre del proyecto    24
ship_addr_line         24
map_page               24
dtype: int64

In [8]:
# Despite many trucks having the same start_time and at_plant_time theoretically, it is impossible that the same truck has the same start_time and at_plant_time
# Therefore, these are duplicates that should be removed, as they are likely to be errors in the data entry process.
remissions_df = remissions_df.drop(typed_time_duplicates.index)
print("Number of rows after dropping duplicates:", remissions_df.shape[0])

Number of rows after dropping duplicates: 340220